add bluesim

diff --git a/core/start-blueos-core b/core/start-blueos-core
--- a/core/start-blueos-core
+++ b/core/start-blueos-core
@@ -35,14 +35,14 @@ TOTAL_RAM_MB=$(free -m | awk '/Mem:/ {print $2}')
 echo "Total RAM size: ${TOTAL_RAM_MB} MB"
 
 # Update docker binds, if we need to restart, exit!
-blueos_startup_update
+#blueos_startup_update
 
 # Set permission of docker unix socket file to be accessible by nginx
-if [ -e "/var/run/docker.sock" ]; then
-    chmod 777 /var/run/docker.sock
-else
-    echo "Error: Docker socket file does not exist!"
-fi
+#if [ -e "/var/run/docker.sock" ]; then
+#    chmod 777 /var/run/docker.sock
+#else
+#    echo "Error: Docker socket file does not exist!"
+#fi
 
 # Generate hardware identification uuid
 if [ -e "/etc/blueos" ]; then
@@ -50,6 +50,12 @@ if [ -e "/etc/blueos" ]; then
 else
     echo "Error: blueos static system configuration folder does not exist!"
 fi
+
+# Define the log file path
+LOG_FILE="/var/logs/start-blueos-core/service_restarts.log"
+
+# Ensure the log directory exists
+sudo mkdir -p $(dirname "$LOG_FILE")
 
 # This is a workaround to make the container's `resolv.conf` synchronized with the host's
 # `resolv.conf`. To do that, we disallow docker from managing the container's DNS nameservers
@@ -71,15 +77,15 @@ fi
 # the BlueOS Helper's internet connection check. By syncing the container's resolv.conf with the
 # host's one, we make sure the container's DNS configuration follows the host's changes, thus,
 # ensuring the container is able to resolve DNSs correctly.
-HOST_RESOLV_CONF=/etc/resolv.conf.host
-if [ -f "$HOST_RESOLV_CONF" ]; then
-    echo "Using host's resolv.conf instead of the one from the docker"
-    umount /etc/resolv.conf
-    rm /etc/resolv.conf
-    ln -s $HOST_RESOLV_CONF /etc/resolv.conf
-else
-    echo "Waring: Using dockers's resolv.conf, this may cause DNS issues if the host's network configuration changes."
-fi
+#HOST_RESOLV_CONF=/etc/resolv.conf.host
+#if [ -f "$HOST_RESOLV_CONF" ]; then
+#    echo "Using host's resolv.conf instead of the one from the docker"
+#    umount /etc/resolv.conf
+#    rm /etc/resolv.conf
+#    ln -s $HOST_RESOLV_CONF /etc/resolv.conf
+#else
+#    echo "Waring: Using dockers's resolv.conf, this may cause DNS issues if the host's network configuration changes."
+#fi
 
 # These services have priority because they do the fundamental for the vehicle to work,
 # and by initializing them first we reduce the time users have to wait to control the vehicle.
@@ -88,9 +94,9 @@ fi
 # From that 1min30s, the startup time is about ~25s, and originally, ~37s, meaning that the
 # remaining (~65 seconds) is the docker shutting down, and the Linux booting up.
 PRIORITY_SERVICES=(
-    'autopilot',0,"nice --19 $SERVICES_PATH/ardupilot_manager/main.py"
+    'autopilot',0,"nice --19 $SERVICES_PATH/ardupilot_manager/main.py -s"
     'cable_guy',0,"$SERVICES_PATH/cable_guy/main.py"
-    'video',0,"nice --19 mavlink-camera-manager --default-settings BlueROVUDP --mavlink tcpout:127.0.0.1:5777 --mavlink-system-id $MAV_SYSTEM_ID --gst-feature-rank omxh264enc=0,v4l2h264enc=250,x264enc=260 --log-path /var/logs/blueos/services/mavlink-camera-manager --verbose"
+    'video',0,"while ! ss -tln | grep -q ':8554'; do sleep 1; done && sleep 5 && nice --19 mavlink-camera-manager --default-settings BlueROVUDP --mavlink tcpout:127.0.0.1:5777 --gst-feature-rank omxh264enc=0,v4l2h264enc=250,x264enc=260 --log-path /var/logs/blueos/services/mavlink-camera-manager --verbose  --stun-server stun://stun.l.google.com:19302 --signalling-server=ws://0.0.0.0:$BLUEOS_SIGNALING_SERVER_PORT"
     'mavlink2rest',0,"mavlink2rest --connect=udpin:127.0.0.1:14000 --server 0.0.0.0:6040 --system-id $MAV_SYSTEM_ID --component-id $MAV_COMPONENT_ID_ONBOARD_COMPUTER4"
 )
 
@@ -113,6 +119,7 @@ SERVICES=(
     'nginx',250,"nice -18 nginx -g \"daemon off;\" -c $TOOLS_PATH/nginx/nginx.conf"
     'log_zipper',250,"nice -20 $SERVICES_PATH/log_zipper/main.py '/shortcuts/system_logs/\\\\*\\\\*/\\\\*.log' --max-age-minutes 60"
     'bag_of_holding',250,"$SERVICES_PATH/bag_of_holding/main.py"
+    'cockpit',0,"/usr/bin/simple-http-server --port  $BLUEOS_COCKPIT_PORT --index /cockpit"
 )
 
 tmux -f /etc/tmux.conf start-server
@@ -140,9 +147,7 @@ function create_service {
         VALUE=${!NAME}
         tmux setenv -t $SESSION_NAME -g $NAME $VALUE
     done
-
-    # Use run_service to start the service with the memory limit
-    tmux send-keys -t $SESSION_NAME "run-service '$command' $memory_limit_mb" C-m
+    tmux send-keys -t $SESSION_NAME "$2" C-m
 }
 
 echo "Starting high priority services.."
